name: Deploy

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    paths-ignore:
      - '**/.gitignore'
      - '**/*.yml'
      - '**/*.md'
      - '**/CODEOWNERS'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm test

      - name: Run E2E
        run: npm run e2e

      - name: Build project
        run: npm run build
